[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#000000"
idle_fg = "#848089"

good_fg = "#F85E84"
good_bg = { link = "idle_bg" }

warning_fg = "#E5C463"
warning_bg = { link = "idle_bg" }

critical_fg = "#EF9062"
critical_bg = { link = "idle_bg" }

[icons]
icons = "awesome6"

[[block]]
block = "music"

[[block]]
block = "kdeconnect"

[[block]]
block = "memory"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "net"

[[block]]
block = "time"
interval = 5

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
